Before new an event or contributor, program will test whether a string is empty or null. If true, no name or date can be set. This is due to the following error.
java.lang.IllegalArgumentException: Value cannot be null or an empty string
	au.edu.ausstage.networks.types.Collaborator.setGivenName(Collaborator.java:121)
	au.edu.ausstage.networks.ProtovisEventCentricManager.getContributorDetail(ProtovisEventCentricManager.java:535)
	au.edu.ausstage.networks.ProtovisEventCentricManager.toJSON(ProtovisEventCentricManager.java:389)
	au.edu.ausstage.networks.ProtovisEventCentricManager.getData(ProtovisEventCentricManager.java:169)
	au.edu.ausstage.networks.ProtovisServlet.doGet(ProtovisServlet.java:157)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)